import ContactUs from "./Contact-us/ContactUs";
import Login from "./Login/Login";
import Home from "./Home/Home";
import Setting from "./Setting/Setting";
import Category from "./Category/Category";
import Item from "./Item/Item";
import Orders from "./Orders/Orders";
import Payment from "./Payment/Payment";
import Page404 from "./Page404/Page404";
export {ContactUs, Login, Home, Setting, Category, Item, Orders, Payment, Page404};
